source 'https://rubygems.org'

gem 'watir'
gem 'data_magic'
gem 'page-object'
gem 'cucumber'
gem 'rspec-expectations'
gem 'pusher'
gem 'require_all'
gem 'parallel_cucumber'
gem 'allure-cucumber'
gem 'syntax', '~> 1.2'
gem 'test-unit'
gem 'headless'
gem 'rake'